create/urls.py
from django.urls import path

from . import views


app_name = 'create'

urlpatterns = [
    path("", views.create, name="create")
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>", views.display_entry, name="display_entry"),
]

randomwiki/urls.py
from django.urls import path

from . import views

app_name = 'randomwiki'

urlpatterns = [
    path("", views.randomwiki, name="randomwiki")
]

search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path("", views.index, name='index'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('search/', include("search.urls")),
    path('create/', include("create.urls")),
    path('randomwiki/', include("randomwiki.urls"))
]

create/models.py
from django.db import models

# Create your models here.

encyclopedia/models.py
from django.db import models

# Create your models here.

randomwiki/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

create/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from encyclopedia import util

# Create your views here.
def create(request):
    if request.method == 'POST':
        title = request.POST['title']
        text = request.POST['wiki-text']
        caseFoldEntries = [entry.casefold() for entry in util.list_entries()]

        if title.casefold() not in caseFoldEntries and title is not '':
            util.save_entry(title, text)
            return HttpResponseRedirect(f'/{title}')
        elif title is '':
            return render(request, 'create/create.html')
        else:
            messages.add_message(request, messages.ERROR, f'A wiki entry with the title {title} already exists.')
            return render(request, 'create/create.html', {'text': text})

    return render(request, 'create/create.html')

encyclopedia/views.py
from django.shortcuts import render

from . import util

from markdown2 import Markdown

from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

markdowner = Markdown()

# display a list of all wiki entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })


# display a wiki entry
def display_entry(request, entry):
    entry_markdown = util.get_entry(entry)
    if entry_markdown is None:
        return render(request, "encyclopedia/entry.html", {"entry_html": "<h1>That entry does not exist.</h1>"})

    entry_html = markdowner.convert(entry_markdown)
    return render(request, "encyclopedia/entry.html", {"entry_html": entry_html, "title": entry})



 

randomwiki/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from random import choice
from encyclopedia import util

# Create your views here.
def randomwiki(request):
    wikiList = util.list_entries()
    randomArticle = choice(wikiList)
    return HttpResponseRedirect(f'/{randomArticle}')

search/views.py
from encyclopedia.views import display_entry
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from encyclopedia import util


# Create your views here.

# search for a wiki entry
def index(request):
    # get value from search box
    if request.method == 'POST':
        value = request.POST['q']
        
        # check to see if the word typed is a valid page. If so, go there.
        if util.get_entry(value) is not None:
            return HttpResponseRedirect(f'/{value}')

        # if not in list, check to see if typed search is a substring of any titles and display a results list.
        entries = util.list_entries()
        filteredEntries = [entry for entry in entries if value.casefold() in entry.casefold()]

        if filteredEntries == []:
            notFoundResponse = 'There are no entries that match that search.'
            return render(request, 'search/index.html', {'notFoundResponse': notFoundResponse})

        return render(request, 'search/index.html', {'filteredEntries': filteredEntries})

create/templates/create/create.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    New Wiki
{% endblock %}

{% block body %}

    <h1>Create a new wiki article</h1>
    <h3> {{ error_message }} </h3>
    <p>Enter your text in markdown. Press the save button when finished.</p>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="/create/" method="post">
        {% csrf_token %}
        <label for="title">Wiki Title</label>
        <input type="text" id="title" name="title">
        <input type="submit" value="Save Wiki">
        <textarea name="wiki-text">
        {{text}}
        </textarea>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<div>{{ entry_html|safe }}</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/search/" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'create:create' %}">Create New Page</a>          
                </div>
                <div>
                    <a href="{% url 'randomwiki:randomwiki' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

search/templates/search/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <h2>{{notFoundResponse}}</h2>
    <ul>
        {% for entry in filteredEntries %}
            <li><a href="{% url 'encyclopedia:display_entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}